### ISSUE TITLE
Sign-up sign-in authentication

### ISSUE THREAD

**Issue by SodaVolcano** [codersforcauses/penni#124]
## Banana.
- **Sign-up** Should be done in #134 
    - [ ] Email - step button `onClick`: POST request, check if email exist in database, show error message if not and deactivate button
    - [ ] Same for name
    - [ ] Password - button is `onSubmit`,  send POST request to server and receive a token from server
    - [ ] Then, get user info and make another POST request to store extra info
- [ ] On sign-in, send POST request to send login credential #135 
- [ ] Rount to different pages depending if `poster` or `bidder` **not included in this issue**
- [ ] Add repeat password input to sign-up #134 
- [ ] #150  (#134  #135)
- [ ] Make axios middleware - append token onto every request **Solve this in this issue**
- [ ] Send get request whenever need to get data from db #22

**Comment by ErikaKK** [comment]
This needs to be tested later

**Comment by ErikaKK** [comment]
I tested the interceptor in #150 and it worked fine so I'll close this issue
