### ISSUE TITLE
Task Card Component

### ISSUE THREAD

**Issue by SodaVolcano** [codersforcauses/penni#33]
Description for a single task from the bidder

![image](https://github.com/codersforcauses/penni/assets/100743188/f4277ce9-acb4-4141-8f11-aff56cfa3a26)
![image](https://github.com/codersforcauses/penni/assets/100743188/cdb92167-3b55-4ef9-a977-929d2cb37f37)
![image](https://github.com/codersforcauses/penni/assets/100743188/8b1f283d-e19e-4600-85ae-04252bfd2db1)

## TODOs
- [x] Empty div with rounded border
- [x] Bid title (e.g. "Clean up my house")
- [x] Category subheading (e.g. "CLEANING")
- [x] Tag Component ("BIDDING", "EXPIRED"), **OPTIONAL**
     - [x] Item changes colour depending on tag (e.g. graying out when EXPIRED)
- [x] Double column description tray (time, location, hours, price)
    - [x] Icon-text pair for the left column items
    - [x] Price and text underneath for the right column item
