### ISSUE TITLE
Callout Components

### ISSUE THREAD

**Issue by SodaVolcano** [codersforcauses/penni#36]
![image](https://github.com/codersforcauses/penni/assets/100743188/d0f880b8-d8f1-41ea-818b-46418db831cd)
![image](https://github.com/codersforcauses/penni/assets/100743188/c4d74e1a-987b-48aa-a72f-4b00021ac8ec)

## General Information
- **location:** `/components`
- **purpose:** Displays information such as error (login, bidding error)
- **behaviour:** take in parameters: text, icon, colour

## TODOs
- [x] Displaying a text with correct styling
- [x] (i) Icon displayed on the left
- [x] Colour parameter, changes colour of whole component
