### ISSUE TITLE
Input Components

### ISSUE THREAD

**Issue by SodaVolcano** [codersforcauses/penni#49]
## Basic Information
Create a `Field` component and a collection of `Input` components that can be inserted into a `Form` (using slots perhaps?). A `Field` consists of labels (title, subheading) and *one or more* input (single-line, numeric, date etc...) (also inserted using slots?).

Something like this?
```html
<Field heading="gimme ur credit card info" subheading="pls">
   <SingleLineInput description="card info here :)" />
   <DropdownInput options=.../>
</Field>
```

**Optional** means an element may or may not be displayed.

- **Location**: `/components/ui/field.tsx`
- **Behaviour**: `Field` is able to have **one or more** input components.
- **Purpose**: Required by #48 

## TODOs
- [x] ~~`Field` component styling: heading, _optional_ subheading~~ **might be uneccesary**
    - ![image](https://github.com/codersforcauses/penni/assets/100743188/00536bc3-551a-44fe-b6d9-41b098c76db3)
- [x] `Input` component styling: *optional* input description
    - ![image](https://github.com/codersforcauses/penni/assets/100743188/ce4eeee0-2962-41a1-890f-cfeb246f6a91)
- [x] Style for when the input component is selected (remove background?)
    - ![image](https://github.com/codersforcauses/penni/assets/100743188/8c0a8ec1-6bd6-49e3-908b-8c9030d77e8d)
- [x] Create the following input components in `field.tsx`
    - [x] `SingleLineInput` input component
    - [x] `ParagraphInput` component
    - ![image](https://github.com/codersforcauses/penni/assets/100743188/bb7d2ea8-626c-47ba-b622-d62e231fecda)
    - [x] `DropdownInput` component
        - ![image](https://github.com/codersforcauses/penni/assets/100743188/9cb418ae-2642-4acf-a6c3-09518c08c5ef)
    - [x] `PriceInput` component; can extend from `SingleLineInput`
        - ![image](https://github.com/codersforcauses/penni/assets/100743188/4edab727-6fa6-46d9-a27a-201220387add)
